-- AlterTable
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "viewCount" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "PageView" ADD COLUMN IF NOT EXISTS "referrer" VARCHAR(512);
ALTER TABLE "PageView" ADD COLUMN IF NOT EXISTS "userAgent" VARCHAR(512);
